# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "axios"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "classnames"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "husky"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "next"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "prettier"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "react"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "react-dom"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "@type/node"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "@type/react"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "@type/react-dom"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "autoprefixer"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "eslint"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "prettier"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "eslint-config-next"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "eslint-plugin-prettier"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "eslint-plugin-unused-imports"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "postcss"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "tailwindcss"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "typescript"
    directory: "/"
    schedule:
      interval: "weekly"